apiVersion: v1
kind: Pod
metadata:
  name: simple-pod3

spec:
  hostPID: true
  containers:
    - name: shell
      imagePullPolicy: IfNotPresent
      image: busybox
      tty: true
      stdin: true

    - name: nginx
      imagePullPolicy: IfNotPresent
      image: nginx:1.8

    - name: hello-world
      imagePullPolicy: IfNotPresent
      image: hello-world